XPoss/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XPos.Repository;
using XPos.ViewModel;

namespace XPoss.Controllers
{
    public class OrderController : Controller
    {
        // GET: Order
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SelectedProduct(int id)
        {
            ProductViewModel product = ProductRepo.GetbyId(id);
            OrderDetailViewModel detail = new OrderDetailViewModel();
            detail.ProductId = product.Id;
            detail.ProductName = product.Name;
            detail.Price = product.Price;
            detail.Stocks = product.Stocks;
            return PartialView("_SelectedProduct", detail);

        }

        [HttpPost]
        public ActionResult Payment(OrderHeaderViewModel model)
        {
            return PartialView("_Payment", model);
        }

        [HttpPost]
        public ActionResult Pay (OrderHeaderViewModel model)
        {
            ResultOrder result = OrderRepo.Post(model);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message,
                    reference = result.Reference
                }, JsonRequestBehavior.AllowGet);
        }
    }
}

XPoss/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XPos.Repository;
using XPos.ViewModel;

namespace XPoss.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(int page = 1, int count = 10)
        {
            var ListProduct = ProductRepo.GetAll(page, count);
            decimal pageTotal = (decimal)ListProduct.Item2 / count;
            int fullPage = ListProduct.Item2 / count;

            if (pageTotal - fullPage > 0)
            {
                fullPage += 1;
            }
            ViewBag.PageTotal = fullPage;
            return PartialView("_List", ListProduct.Item1);
        }

        //public ActionResult List()
        //{
        //List<ProductViewModel> ListVariant = ProductRepo.GetAll();
        //return PartialView("_List", ListVariant);
        //}

        public ActionResult ActiveList(string Name)
        {
            return PartialView("_List", ProductRepo.GetActiveList(Name));
        }

        public ActionResult NonactiveList(string Name)
        {
            return PartialView("_List", ProductRepo.GetNonactiveList(Name));
        }

        public ActionResult OrderAscList(string Name)
        {
            return PartialView("_List", ProductRepo.GetByAscending(Name));
        }

        public ActionResult OrderDescList(string Name)
        {
            return PartialView("_List", ProductRepo.GetByDescending(Name));
        }

        public ActionResult ProductList(string search ="")
        {
            return PartialView("_List", ProductRepo.GetBySearch(search));
        }

        public ActionResult ListByVarian(long Id = 0)
        {
            return PartialView("_ListByVarian", ProductRepo.ByVarian(Id));
        }

        public ActionResult ListByCategory(long Id = 0)
        {
            return PartialView("_ListByCategory", VariantRepo.ByCategory(Id));
        }

        public ActionResult Create()
        {
            ViewBag.CategoryList = new SelectList(CategoryRepo.GetAll(), "Id", "Name");
            ViewBag.VarianList = new SelectList(VariantRepo.GetAll(), "Id", "Name");

            //ViewBag.VarianList = new SelectList(VariantRepo.ByCategory(0), "Id", "Name");
            return PartialView("_Create", new ProductViewModel());
        }

        [HttpPost]
        public ActionResult Create(ProductViewModel model)
        {
            ResponseResult result = ProductRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        //edit
        public ActionResult Edit(int id)
        {
            ViewBag.CategoryList = new SelectList(CategoryRepo.GetAll(), "Id", "Name");
            ViewBag.VarianList = new SelectList(VariantRepo.GetAll(), "Id", "Name");
            return PartialView("_Edit", ProductRepo.GetbyId(id));
        }

        [HttpPost]
        public ActionResult Edit(ProductViewModel model)
        {
            ResponseResult result = ProductRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);

        }

        //delete
        public ActionResult Delete(int id)
        {
            return PartialView("_Delete", ProductRepo.GetbyId(id));
        }

        [HttpPost]
        public ActionResult Delete(ProductViewModel model)
        {
            ResponseResult result = ProductRepo.Delete(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);

        }

        public ActionResult ProductListForOrder(string search = "")
        {
            var result = ProductRepo.GetByFilter(search);
            return PartialView("_ProductListForOrder", result.Item1);
        }
    }
}

XPoss/Controllers/VariantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XPos.Repository;
using XPos.ViewModel;

namespace XPoss.Controllers
{
    public class VariantController : Controller
    {
        // GET: Variant
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            List<VariantViewModel> ListVariant = VariantRepo.GetAll();
        return PartialView("_List", ListVariant);
        }

        //public ActionResult List(int page = 1, int count = 10)
        //{
           // var ListProduct = VariantRepo.GetAll(page, count);
           // decimal pageTotal = (decimal)ListProduct.Item2 / count;
           // int fullPage = ListProduct.Item2 / count;

           // if (pageTotal - fullPage > 0)
           // {
          //      fullPage += 1;
           // }
           // ViewBag.PageTotal = fullPage;
           // return PartialView("_List", ListProduct.Item1);
       // }

        public ActionResult ActiveList(string Name)
        {
            return PartialView("_List", VariantRepo.GetActiveList(Name));
        }

        public ActionResult NonactiveList(string Name)
        {
            return PartialView("_List", VariantRepo.GetNonactiveList(Name));
        }

        public ActionResult OrderAscList(string Name)
        {
            return PartialView("_List", VariantRepo.GetByAscending(Name));
        }

        public ActionResult OrderDescList(string Name)
        {
            return PartialView("_List", VariantRepo.GetByDescending(Name));
        }

        public ActionResult VariantList(string search = "")
        {
            return PartialView("_List", VariantRepo.GetBySearch(search));
        }

        public ActionResult ListByCategory(long Id = 0)
        {
            return PartialView("_ListByCategory", VariantRepo.ByCategory(Id));
        }

        //create
        public ActionResult Create()
        {
            ViewBag.CategoryList = new SelectList(CategoryRepo.GetAll(), "Id", "Name");
            return PartialView("_Create", new VariantViewModel());
        }

        [HttpPost]
        public ActionResult Create(VariantViewModel model)
        {
            ResponseResult result = VariantRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        //edit
        public ActionResult Edit(int id)
        {
            ViewBag.CategoryList = new SelectList(CategoryRepo.GetAll(), "Id", "Name");
            return PartialView("_Edit", VariantRepo.GetbyId(id));
        }

        [HttpPost]
        public ActionResult Edit(VariantViewModel model)
        {
            ResponseResult result = VariantRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);

        }

        //delete
        public ActionResult Delete(int id)
        {
            return PartialView("_Delete", VariantRepo.GetbyId(id));
        }

        [HttpPost]
        public ActionResult Delete(VariantViewModel model)
        {
            ResponseResult result = VariantRepo.Delete(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);

        }
    }
}

XPoss/Views/Product/_Create.cshtml
@model XPos.ViewModel.ProductViewModel


@using (Html.BeginForm("Create", "Product", FormMethod.Post, 
    new { id = "form-create", name = "form-create", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.CategoryId, (IEnumerable<SelectListItem>)ViewBag.CategoryList,
              "--- select category ---", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.VariantId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.VariantId, (IEnumerable<SelectListItem>)ViewBag.VarianList,
               "--- select variant ---", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.VariantId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Initial, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Initial, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Initial, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Active)
                @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Stocks, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Stocks, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Stocks, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="button" value="Cancel" data-dismiss="modal" class="btn btn-default" />
            <input type="reset" value="Reset" class="btn btn-primary" />
            <input type="submit" value="Create" class="btn btn-success" />
        </div>
    </div>
</div>
}
@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
    $("#CategoryId").change(function () {
        $.ajax({
            url: '@Url.Action("ListByCategory", "Variant")',
            type: 'get',
            data: { id: $(this).val() },
            success: function (result) {
                $("#VariantId").html(result);
            }
        })
    });

    $("#form-create").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {

                    alert("Save successfull! Name: " + result.entity.Name);
                    $(".modal").modal("hide");
                    GetList();
                }
                else {
                    alert("Error! " + result.message);
                }
            }
        });
        return false;
    });
</script>

XPoss/Views/Product/_Delete.cshtml
@model XPos.ViewModel.ProductViewModel

<h3>Are you sure you want to delete this Product?</h3>
<div>

    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Initial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Initial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stocks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stocks)
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "Product", FormMethod.Post,
      new { id = "form-delete", name = "form-delete" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)

        <div class="form-actions no-color">
            <input type="button" value="Cancel" data-dismiss="modal" class="btn btn-default" />
            <input type="submit" value="Yes" class="btn btn-danger" />
        </div>
    }
</div>

<script type="text/javascript">
        $("#form-delete").submit(function () {
            $.ajax({
                url: this.action,
                type: this.method,
                data: $(this).serialize(),
                success: function (result) {
                    if (result.success) {
                        alert("Delete successfull!");
                        $(".modal").modal("hide");
                        GetList();
                    }
                    else {
                        alert("Error! " + result.message);
                    }
                }
            });
            return false;
        });
</script>

XPoss/Views/Product/_Edit.cshtml
@model XPos.ViewModel.ProductViewModel


@using (Html.BeginForm("Edit", "Product", FormMethod.Post,
    new { id = "form-edit", name = "form-edit" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.CategoryId, (IEnumerable<SelectListItem>)ViewBag.CategoryList,
               "--- select category ---", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.VariantId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.VariantId, (IEnumerable<SelectListItem>)ViewBag.VarianList,
               "--- select variant ---", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.VariantId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Initial, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Initial, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Initial, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Active)
                @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Stocks, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Stocks, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Stocks, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="button" value="Cancel" data-dismiss="modal" class="btn btn-default" />
            <input type="submit" value="Save" class="btn btn-warning" />
        </div>
    </div>
</div>
}

<script type="text/javascript">
    $("#form-edit").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {

                    alert("Edit successfull! Name: " + result.entity.Name);
                    $(".modal").modal("hide");
                    GetList();
                }
                else {
                    alert("Error! " + result.message);
                }
            }
        });
        return false;
    });
</script>

XPoss/Views/Product/_List.cshtml
@model IEnumerable<XPos.ViewModel.ProductViewModel>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Initial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Active)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stocks)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Initial)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Active)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Stocks)
            </td>
            <td>
                <div class="btn-group btn-group-sm">
                    <button type="button" class="btn btn-warning btn-edit" data-id="@item.Id" title="Edit">
                        <span class="glyphicon glyphicon-edit" aria-hidden="true">
                        </span>
                    </button>
                </div>
                <div class="btn-group btn-group-sm">
                    <button type="button" class="btn btn-danger btn-delete" data-id="@item.Id" title="Delete">
                        <span class="glyphicon glyphicon-trash" aria-hidden="true">
                        </span>
                    </button>
                </div>
            </td>
        </tr>
}
    </tbody>
    <tfoot>
        <tr>
            <th colspan="9">
                <nav aria-label="Page Navigation">
                    <ul class="pagination">
                        <li>
                            <a href="#" aria-label="Previous" onclick="MoveToPage(-1)">
                                <span aria-hidden="true">&laquo;  </span>
                            </a>
                        </li>
                        @{ for (int i = 0; i < ViewBag.PageTotal; i++)
                                        {
                            <li><a href="#" class="btn-page">@(i + 1)</a></li> } }
                        <li>
                            <a href="#" aria-label="Next" onclick="MoveToPage(1)">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </th>
        </tr>
    </tfoot>
</table>

<script type="text/javascript">
    $(document).ready(function () {
        $(".pagination li").eq(selPage).addClass('active');
        maxPage = @ViewBag.PageTotal;
    });

    $(".btn-edit").click(function () {
		$.ajax({
			url: '@Url.Action("Edit", "Product")',
            type: 'get',
            data: {id: $(this).attr("data-id")},
			success: function (result) {
				$(".modal-title").html("Edit - Product");
				$(".modal-body").html(result);
				$(".modal").modal("show");
			}
		});
    });

    $(".btn-delete").click(function () {
		$.ajax({
			url: '@Url.Action("Delete", "Product")',
            type: 'get',
            data: {id: $(this).attr("data-id")},
			success: function (result) {
				$(".modal-title").html("Delete - Product");
				$(".modal-body").html(result);
				$(".modal").modal("show");
			}
		});
    });

    $(".btn-page").click(function () {
        selPage = $(this).html();
        $(".pagination li").eq(selPage).addClass('active');
        $(".pagination li").not(':eq(' + selPage + ')').removeClass('active');
        GetList(selPage);
    })


</script>

XPoss/Views/Product/_ListByVarian.cshtml
@model IEnumerable<XPos.ViewModel.ProductViewModel>

<option value="">Select Product</option>
@foreach (var item in Model)
{
    <option value="@item.Id">@item.Name</option>
}

XPoss/Views/Product/_ProductListForOrder.cshtml
@model IEnumerable<XPos.ViewModel.ProductViewModel>
<d>
    <div style="display: flex; justify-content: flex-end">
        <div class="btn-group btn-group-sm">
            <input type="text" id="txt-search" class="form-control form-group-lg" placeholder="Search..." />
        </div>
        &nbsp;
        <div class="btn-group btn-group-md">
            <button type="button" class="btn btn-default btn-search" title="Search">
                <span class="glyphicon glyphicon-search" aria-hidden="true">
                </span>
            </button>
        </div>
    </div>
</d>


<table class="table">
    <thead>
        <tr>
            <th>Select</th>
            <th>
                @Html.DisplayNameFor(model => model.Initial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stocks)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <button type="button" class="btn btn-success btn-select" 
                            data-dismiss="modal" data-id="@item.Id" title="Select">
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                    </button>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Initial)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Stocks)
                </td>
            </tr>
        }
    </tbody>
</table>

<script type="text/javascript">
   
    $(".btn-select").click(function () {
        $.ajax({
            url: '@Url.Action("SelectedProduct", "Order")',
            type: 'get',
            data: { id: $(this).attr("data-id") },
            success: function (result) {
                $("#order-table tbody").append(result);
                Summary();
            }
        })
    });

    $(".btn-search").click(function () {
		$.ajax({
			url: '@Url.Action("ProductListForOrder", "Product")',
            type: 'get',
            data: { search: $("#txt-search").val() },
			success: function (result) {
                $(".modal-body").html(result);
			}
		});
    });
</script>